using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace GS.Game.Generators {
	[Generator(LanguageNames.CSharp)]
	public sealed class CommandGenerator : IIncrementalGenerator {
		public void Initialize(IncrementalGeneratorInitializationContext context) {
			var commandTypes = context.CompilationProvider
				.Select(static (comp, _) => GetCommandTypes(comp));

			context.RegisterSourceOutput(commandTypes, static (ctx, types) => {
				if (types.Count == 0) return;
				ctx.AddSource("CommandBuffers.g.cs", BuildBuffers(types));
				ctx.AddSource("CommandAccessor.g.cs", BuildAccessor(types));
			});
		}

		static IReadOnlyList<CommandTypeInfo> GetCommandTypes(Compilation comp) {
			var iCommandSymbol = comp.GetTypeByMetadataName("GS.Game.Commands.ICommand");
			if (iCommandSymbol == null) return ImmutableArray<CommandTypeInfo>.Empty;

			var result = new List<CommandTypeInfo>();
			CollectCommandTypes(comp.GlobalNamespace, iCommandSymbol, result);
			return result;
		}

		static void CollectCommandTypes(
			INamespaceOrTypeSymbol ns,
			INamedTypeSymbol iCommand,
			List<CommandTypeInfo> result) {
			if (ns is INamespaceSymbol nsSymbol) {
				foreach (var member in nsSymbol.GetNamespaceMembers())
					CollectCommandTypes(member, iCommand, result);
				foreach (var type in nsSymbol.GetTypeMembers())
					CollectCommandTypes(type, iCommand, result);
			} else if (ns is INamedTypeSymbol typeSymbol) {
				if (!typeSymbol.IsAbstract && typeSymbol.TypeKind != TypeKind.Interface
					&& typeSymbol.AllInterfaces.Any(
						i => SymbolEqualityComparer.Default.Equals(i, iCommand))) {
					result.Add(new CommandTypeInfo(
						typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
						typeSymbol.Name
					));
				}
				foreach (var nested in typeSymbol.GetTypeMembers())
					CollectCommandTypes(nested, iCommand, result);
			}
		}

		static string BuildBuffers(IReadOnlyList<CommandTypeInfo> types) {
			var sb = new StringBuilder();
			sb.AppendLine("// <auto-generated/>");
			sb.AppendLine("#nullable enable");
			sb.AppendLine("using System.Collections.Generic;");
			sb.AppendLine("using GS.Game.Commands;");
			sb.AppendLine();
			sb.AppendLine("namespace GS.Main {");

			foreach (var t in types) {
				string bufferName = t.SimpleName + "CommandBuffer";
				sb.AppendLine($"\tsealed class {bufferName} {{");
				sb.AppendLine($"\t\treadonly List<{t.FullName}> _items = new List<{t.FullName}>();");
				sb.AppendLine($"\t\tpublic void Add({t.FullName} cmd) => _items.Add(cmd);");
				sb.AppendLine($"\t\tpublic ReadCommands<{t.FullName}> AsCommands() =>");
				sb.AppendLine($"\t\t\tnew ReadCommands<{t.FullName}>(_items.ToArray());");
				sb.AppendLine($"\t\tpublic void Clear() => _items.Clear();");
				sb.AppendLine($"\t}}");
				sb.AppendLine();
			}

			sb.AppendLine("}");
			return sb.ToString();
		}

		static string BuildAccessor(IReadOnlyList<CommandTypeInfo> types) {
			var sb = new StringBuilder();
			sb.AppendLine("// <auto-generated/>");
			sb.AppendLine("#nullable enable");
			sb.AppendLine("using System;");
			sb.AppendLine("using GS.Game.Commands;");
			sb.AppendLine();
			sb.AppendLine("namespace GS.Main {");
			sb.AppendLine("\tpartial class CommandAccessor : IWriteOnlyCommandAccessor, IReadOnlyCommandAccessor {");
			sb.AppendLine();

			// Fields
			foreach (var t in types) {
				string bufferName = t.SimpleName + "CommandBuffer";
				sb.AppendLine($"\t\t{bufferName} {FieldName(t.SimpleName)} = new {bufferName}();");
			}
			sb.AppendLine();

			// Typed read accessors
			foreach (var t in types) {
				sb.AppendLine($"\t\tpublic ReadCommands<{t.FullName}> Read{t.SimpleName}() => {FieldName(t.SimpleName)}.AsCommands();");
			}
			sb.AppendLine();

			// IWriteOnlyCommandAccessor.Push
			sb.AppendLine("\t\tvoid IWriteOnlyCommandAccessor.Push<TCommand>(TCommand cmd) {");
			bool first = true;
			foreach (var t in types) {
				string keyword = first ? "if" : "else if";
				sb.AppendLine($"\t\t\t{keyword} (typeof(TCommand) == typeof({t.FullName}))");
				sb.AppendLine($"\t\t\t\t{FieldName(t.SimpleName)}.Add(({t.FullName})(object)cmd!);");
				first = false;
			}
			sb.AppendLine("\t\t\telse");
			sb.AppendLine("\t\t\t\tthrow new InvalidOperationException(");
			sb.AppendLine("\t\t\t\t\t$\"Unknown command type {typeof(TCommand).Name}\");");
			sb.AppendLine("\t\t}");
			sb.AppendLine();

			// IReadOnlyCommandAccessor.Read
			sb.AppendLine("\t\tReadCommands<TCommand> IReadOnlyCommandAccessor.Read<TCommand>() {");
			first = true;
			foreach (var t in types) {
				string keyword = first ? "if" : "else if";
				sb.AppendLine($"\t\t\t{keyword} (typeof(TCommand) == typeof({t.FullName}))");
				sb.AppendLine($"\t\t\t\treturn (ReadCommands<TCommand>)(object){FieldName(t.SimpleName)}.AsCommands();");
				first = false;
			}
			sb.AppendLine("\t\t\tthrow new InvalidOperationException(");
			sb.AppendLine("\t\t\t\t$\"Unknown command type {typeof(TCommand).Name}\");");
			sb.AppendLine("\t\t}");
			sb.AppendLine();

			// Clear
			sb.AppendLine("\t\tinternal void Clear() {");
			foreach (var t in types)
				sb.AppendLine($"\t\t\t{FieldName(t.SimpleName)}.Clear();");
			sb.AppendLine("\t\t}");
			sb.AppendLine();

			sb.AppendLine("\t}");
			sb.AppendLine("}");
			return sb.ToString();
		}

		static string FieldName(string simpleName) =>
			"_" + char.ToLower(simpleName[0]) + simpleName.Substring(1) + "Buffer";

		sealed class CommandTypeInfo {
			public string FullName { get; }
			public string SimpleName { get; }
			public CommandTypeInfo(string fullName, string simpleName) {
				FullName = fullName;
				SimpleName = simpleName;
			}
		}
	}
}
