<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latestMajor</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../ECS.Viewer/ECS.Viewer.csproj" />
    <ProjectReference Include="../ECS.Viewer.Host/ECS.Viewer.Host.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
