using Microsoft.CodeAnalysis;
using System.Text;

namespace ECS.Generators {
	[Generator(LanguageNames.CSharp)]
	public sealed class QueryGenerator : IIncrementalGenerator {
		public void Initialize(IncrementalGeneratorInitializationContext context) {
			// Only emit code when compiling ECS.Core (identified by assembly name)
			var isEcsCore = context.CompilationProvider
				.Select(static (comp, _) => comp.AssemblyName == "ECS.Core");

			context.RegisterSourceOutput(isEcsCore, static (ctx, isCore) => {
				if (!isCore) return;
				ctx.AddSource("QueryCallbacks.g.cs", BuildCallbacks());
				ctx.AddSource("WorldQueryMethods.g.cs", BuildWorldMethods());
			});
		}

		static string BuildCallbacks() {
			var sb = new StringBuilder();
			sb.AppendLine("// <auto-generated/>");
			sb.AppendLine("#nullable enable");
			sb.AppendLine("namespace ECS {");
			for (int n = 1; n <= 4; n++) {
				string typeParams = TypeParams(n);
				string refParams = RefParams(n);
				sb.AppendLine(
					$"\tpublic delegate void QueryCallback<{typeParams}>(int entity, {refParams});");
			}
			sb.AppendLine("}");
			return sb.ToString();
		}

		static string BuildWorldMethods() {
			var sb = new StringBuilder();
			sb.AppendLine("// <auto-generated/>");
			sb.AppendLine("#nullable enable");
			sb.AppendLine("namespace ECS {");
			sb.AppendLine("\tpublic sealed partial class World {");

			for (int n = 1; n <= 4; n++) {
				string typeParams = TypeParams(n);
				string cbType = $"QueryCallback<{typeParams}>";
				string required = RequiredArray(n);
				string colDecls = ColDecls(n);
				string callArgs = CallArgs(n);
				string builderType = BuilderType(n);

				// Immediate form
				sb.AppendLine($"\t\tpublic void Query<{typeParams}>({cbType} callback) {{");
				sb.AppendLine($"\t\t\tint[] required = {required};");
				sb.AppendLine($"\t\t\tforeach (var arch in GetMatchingArchetypes(required, null)) {{");
				sb.AppendLine(colDecls);
				sb.AppendLine($"\t\t\t\tint count = arch.Count;");
				sb.AppendLine($"\t\t\t\tint[] entities = arch.Entities;");
				sb.AppendLine($"\t\t\t\tfor (int i = 0; i < count; i++)");
				sb.AppendLine($"\t\t\t\t\tcallback({callArgs});");
				sb.AppendLine($"\t\t\t}}");
				sb.AppendLine($"\t\t}}");
				sb.AppendLine();

				// Builder form
				sb.AppendLine(
					$"\t\tpublic {builderType} Query<{typeParams}>() => new {builderType}(this);");
				sb.AppendLine();
			}

			sb.AppendLine("\t}");
			sb.AppendLine("}");
			return sb.ToString();
		}

		static string TypeParams(int n) {
			var parts = new string[n];
			for (int i = 1; i <= n; i++) parts[i - 1] = $"C{i}";
			return string.Join(", ", parts);
		}

		static string RefParams(int n) {
			var parts = new string[n];
			for (int i = 1; i <= n; i++) parts[i - 1] = $"ref C{i} c{i}";
			return string.Join(", ", parts);
		}

		static string RequiredArray(int n) {
			var parts = new string[n];
			for (int i = 1; i <= n; i++) parts[i - 1] = $"TypeId<C{i}>.Value";
			return "{ " + string.Join(", ", parts) + " }";
		}

		static string ColDecls(int n) {
			var sb = new StringBuilder();
			for (int i = 1; i <= n; i++)
				sb.AppendLine($"\t\t\t\tC{i}[] c{i} = arch.GetColumn<C{i}>();");
			return sb.ToString().TrimEnd();
		}

		static string CallArgs(int n) {
			var parts = new string[n + 1];
			parts[0] = "entities[i]";
			for (int i = 1; i <= n; i++) parts[i] = $"ref c{i}[i]";
			return string.Join(", ", parts);
		}

		static string BuilderType(int n) => $"QueryBuilder<{TypeParams(n)}>";
	}
}
